#!/bin/sh
#
# rpi has no RTC configure time
#
# TODO: detect RTC and if any, skip time prompt

start() {
	echo 'Type the following command on your linux prompt:
date --utc +"%Y-%_0m-%_0d %_0k:%_0M"
'
	read -p 'Enter the result here ' date
	date "$date"
}
stop() {
	:
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

