#!/bin/sh
#
# Start rpi hw rng
#

start() {
	modprobe bcm2708-rng
}
stop() {
	modprobe -r bcm2708-rng
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

