#!/bin/sh
#
# Pause for traces to stabilize before passphrase entry
#
set -e

start() {
	sleep 1
}

stop() {
:
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

