#!/bin/sh
#
# Copy/Update easy-rsa configuration to private area
#
set -e

MNT_SHARED="/mnt/shared"
MNT_PRIVATE="/mnt/private"

check_mount() {
	MNT=$1
	if ! grep "$MNT" /proc/self/mounts > /dev/null; then
		echo "ERROR: '$MNT' is not mounted, not updating easy-rsa configuration !!"
		echo "Please run '$0 start' again when mounted."
		exit 1
	fi
}

start() {
	check_mount "$MNT_SHARED"
	check_mount "$MNT_PRIVATE"
	/usr/bin/raspki update
}

stop() {
:
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

